title: Jiny-Css
email: infohojin@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Jiny Study.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://html.jiny.dev" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: infohojin
github_username:  infohojin

source: src
destination: docs

sass:
  load_paths:
    - _sass
    - ../node_modules/bootstrap/scss

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
